//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DistinctBlog.Models.entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLHAKKIMDA
    {
        public byte ID { get; set; }
        public string HAKKIMDA { get; set; }
    }
}
